Repository ForgeFlow/eficent-odoo-addons, pull requests merged in 2019-11, with the labels that each got.

#172 [12.0][MIG]Purchase delivery
  analytic_wip_report/models/account_analytic_account.py
  analytic_wip_report_extend/models/account_analytic_account.py
  analytic_wip_report_fiscalyear/models/account_analytic_account.py
  change_management_contract_value/models/change_management_template.py
  hr_timesheet_sheet_validators/tests/test_hr_timesheet_sheet_validators.py
  hr_timesheet_sheet_validators/views/hr_timesheet_sheet_view.xml
  purchase_delivery/README.rst
  purchase_delivery/__init__.py
  purchase_delivery/__manifest__.py
  purchase_delivery/model/__init__.py
  purchase_delivery/model/account_invoice.py
  purchase_delivery/model/delivery.py
  purchase_delivery/model/purchase.py
  purchase_delivery/tests/__init__.py
  purchase_delivery/tests/test_purchase_delivery.py
  purchase_delivery/view/delivery_view.xml
  purchase_delivery/view/purchase_view.xml
  stock_location_analytic_mrp/models/mrp.py
  stock_location_analytic_mrp/tests/test_stock_location_analytic_mrp.py
Labels: Fixes issue, Needs review, Ready to merge

#175 [MIG][12.0]Purchase stock analytic
  analytic_wip_report_fiscalyear/models/account_analytic_account.py
  purchase_stock_analytic/README.rst
  purchase_stock_analytic/__init__.py
  purchase_stock_analytic/__manifest__.py
  purchase_stock_analytic/models/__init__.py
  purchase_stock_analytic/models/analytic.py
  purchase_stock_analytic/models/purchase.py
  purchase_stock_analytic/models/stock_quant.py
  purchase_stock_analytic/static/description/icon.png
  purchase_stock_analytic/tests/__init__.py
  purchase_stock_analytic/tests/test_purchase_order_line.py
  purchase_stock_analytic/tests/test_purchase_stock_analytic.py
  purchase_stock_analytic/views/purchase_views.xml
Labels: Ready to merge

#183 [12.0][ENH]add migration script from analytic stages to base kanban stages
  project_wbs_stage/migrations/12.0.1.0.0/pre-migration.py
Labels: Ready to merge

#184 [12.0] oca dep
  oca_dependencies.txt
Labels: Fastracking, Ready to merge

#185 [12.0][FIX] purchase stock analytic
  purchase_stock_analytic/views/purchase_views.xml
Labels: Fastracking, Ready to merge

#181 [10.0][ENH]analytic_resource_plan_purchase_request
  analytic_resource_plan_purchase_request/wizard/analytic_resource_plan_line_make_purchase_request.py
  analytic_resource_plan_purchase_request/wizard/analytic_resource_plan_line_make_purchase_request.xml
Labels: Approved, Ready to merge

#188 [12.0][MIG] account_move_category
  account_move_category/README.rst
  account_move_category/__init__.py
  account_move_category/__manifest__.py
  account_move_category/models/__init__.py
  account_move_category/models/account_move.py
  account_move_category/views/account_move_view.xml
Labels: Needs review, Ready to merge

#180 [12.0][MIG] account_analytic_sequence
  account_analytic_post_by_type/tests/test_account_analytic_post.py
  account_analytic_sequence/README.rst
  account_analytic_sequence/__init__.py
  account_analytic_sequence/__manifest__.py
  account_analytic_sequence/data/analytic_account_sequence_data.xml
  account_analytic_sequence/i18n/analytic_account_sequence.pot
  account_analytic_sequence/i18n/it.po
  account_analytic_sequence/i18n/sl.po
  account_analytic_sequence/i18n/zh_CN.po
  account_analytic_sequence/migrations/12.0.1.0.0/noupdate_changes.xml
  account_analytic_sequence/migrations/12.0.1.0.0/post-migration.py
  account_analytic_sequence/migrations/12.0.1.0.0/pre-migration.py
  account_analytic_sequence/models/__init__.py
  account_analytic_sequence/models/account_analytic_account.py
  account_analytic_sequence/models/analytic_account_sequence.py
  account_analytic_sequence/security/ir.model.access.csv
  account_analytic_sequence/static/description/icon.png
  account_analytic_sequence/views/account_analytic_account_view.xml
  account_analytic_sequence/views/analytic_account_sequence_view.xml
  analytic_cost_revenue/tests/test_analytic_cost_revenue.py
Labels: Needs review, Ready to merge

#189 [10.0][FIX] do not filter parent RPL just confirm them as the others
  analytic_resource_plan/wizard/resource_plan_line_change_state.py
  analytic_resource_plan_stock_picking/wizard/delivery.py
Labels: bug

#191 [12.0][MIG] sale_purchase_last_price
  sale_purchase_last_price/README.rst
  sale_purchase_last_price/__init__.py
  sale_purchase_last_price/__manifest__.py
  sale_purchase_last_price/models/__init__.py
  sale_purchase_last_price/models/sale_order_line.py
  sale_purchase_last_price/tests/__init__.py
  sale_purchase_last_price/tests/test_purchase_last_price.py
  sale_purchase_last_price/views/sale_view.xml
Labels: Needs review

#192 [12.0][FIX]analytic_category dependencies
  analytic_category/__manifest__.py
Labels: Fastracking, shame

#196 [12.0][FIX] analytic_resource_plan_stock_picking: don't substitute the context
  analytic_resource_plan_stock_picking/model/analytic_resource_plan_line.py
Labels: enhancement

#197 [12.0][FIX]dates passed to wip report
  analytic_wip_report_fiscalyear/wizards/analytic_wip_report.py
Labels: Fastracking, Fixes issue, shame

#198 [12.0][MIG]Analytic wip report category
  analytic_wip_report_category/README.rst
  analytic_wip_report_category/__init__.py
  analytic_wip_report_category/__manifest__.py
  analytic_wip_report_category/static/src/img/icon.png
  analytic_wip_report_category/wizards/__init__.py
  analytic_wip_report_category/wizards/analytic_wip_report.py
  analytic_wip_report_category/wizards/analytic_wip_report_view.xml
Labels: Functionally tested
