Repository ForgeFlow/eficent-odoo-addons, pull requests merged in 2019-10, with the labels that each got.

#143 [12.0][FIX]better exceptions in analytic_resource_plan
  analytic_resource_plan/wizard/analytic_resource_plan_copy_version.py
Labels: Fastracking

#138 [12.0] mig analytic category
  analytic_category/README.rst
  analytic_category/__init__.py
  analytic_category/__manifest__.py
  analytic_category/models/__init__.py
  analytic_category/models/analytic.py
  analytic_category/models/analytic_category.py
  analytic_category/security/security.xml
  analytic_category/view/analytic_view.xml
  analytic_category/view/category_view.xml
Labels: Ready to merge

#140 [12.0] mig product manufacturer partner
  product_manufacturer_partner/README.rst
  product_manufacturer_partner/__init__.py
  product_manufacturer_partner/__manifest__.py
  product_manufacturer_partner/model/__init__.py
  product_manufacturer_partner/model/partner.py
  product_manufacturer_partner/model/product.py
  product_manufacturer_partner/view/partner_view.xml
  product_manufacturer_partner/view/product_view.xml
Labels: Approved

#139 [12.0] mig project wbs stage
  oca_dependencies.txt
  project_wbs_stage/README.rst
  project_wbs_stage/__init__.py
  project_wbs_stage/__manifest__.py
  project_wbs_stage/models/__init__.py
  project_wbs_stage/models/analytic.py
  project_wbs_stage/models/project.py
  project_wbs_stage/views/account_analytic_account_view.xml
  project_wbs_stage/views/project_project_view.xml
Labels: Approved

#110 [12.0][MIG] project_progress_measurement
  project_progress_measurement/README.rst
  project_progress_measurement/__init__.py
  project_progress_measurement/__manifest__.py
  project_progress_measurement/i18n/project_progress_measurement.pot
  project_progress_measurement/i18n/sl.po
  project_progress_measurement/i18n/zh_CN.po
  project_progress_measurement/models/__init__.py
  project_progress_measurement/models/project_progress_measurement.py
  project_progress_measurement/models/project_project.py
  project_progress_measurement/security/ir.model.access.csv
  project_progress_measurement/static/src/img/progress.png
  project_progress_measurement/views/project_progress_measurement_view.xml
  project_progress_measurement/views/project_project_view.xml
  project_progress_measurement/wizard/__init__.py
  project_progress_measurement/wizard/progress_measurements_entry.py
  project_progress_measurement/wizard/progress_measurements_entry_view.xml
Labels: Approved

#141 [12.0] mig purchase request sale
  oca_dependencies.txt
  purchase_request_sale/README.rst
  purchase_request_sale/__init__.py
  purchase_request_sale/__manifest__.py
  purchase_request_sale/migrations/10.0.1.0.0/post-migration.py
  purchase_request_sale/models/__init__.py
  purchase_request_sale/models/purchase_request.py
  purchase_request_sale/models/sale.py
  purchase_request_sale/models/stock_rule.py
  purchase_request_sale/tests/__init__.py
  purchase_request_sale/tests/test_purchase_request_sale.py
  purchase_request_sale/views/purchase_request_view.xml
Labels: Approved

#144 [12.0][MIG] analytic resource plan purchase request
  account_analytic_cost_category/__manifest__.py
  account_analytic_cost_category/models/account_analytic_account.py
  analytic_location/model/analytic.py
  analytic_resource_plan_purchase_request/README.rst
  analytic_resource_plan_purchase_request/__init__.py
  analytic_resource_plan_purchase_request/__manifest__.py
  analytic_resource_plan_purchase_request/i18n/analytic_resource_plan_purchase_request.pot
  analytic_resource_plan_purchase_request/i18n/sl.po
  analytic_resource_plan_purchase_request/i18n/zh_CN.po
  analytic_resource_plan_purchase_request/model/__init__.py
  analytic_resource_plan_purchase_request/model/analytic_resource_plan_line.py
  analytic_resource_plan_purchase_request/model/purchase_request.py
  analytic_resource_plan_purchase_request/static/description/icon.png
  analytic_resource_plan_purchase_request/tests/__init__.py
  analytic_resource_plan_purchase_request/tests/test_analytic_resource_plan_purchase.py
  analytic_resource_plan_purchase_request/views/analytic_resource_plan_view.xml
  analytic_resource_plan_purchase_request/views/purchase_request_view.xml
  analytic_resource_plan_purchase_request/wizard/__init__.py
  analytic_resource_plan_purchase_request/wizard/analytic_resource_plan_line_make_purchase_request.py
  analytic_resource_plan_purchase_request/wizard/analytic_resource_plan_line_make_purchase_request.xml
  analytic_resource_plan_stock/tests/test_analytic_resource_plan_stock.py
  project_location/model/project.py
  project_location/view/project_view.xml
  stock_location_analytic/__manifest__.py
  stock_location_analytic/views/analytic_view.xml
Labels: Approved

#145 [12.0][MIG] analytic resource plan stock picking
  analytic_resource_plan/tests/test_analytic_resource_plan.py
  analytic_resource_plan_stock_picking/README.rst
  analytic_resource_plan_stock_picking/__init__.py
  analytic_resource_plan_stock_picking/__manifest__.py
  analytic_resource_plan_stock_picking/model/__init__.py
  analytic_resource_plan_stock_picking/model/analytic_resource_plan_line.py
  analytic_resource_plan_stock_picking/model/stock_picking.py
  analytic_resource_plan_stock_picking/tests/__init__.py
  analytic_resource_plan_stock_picking/tests/test_analytic_resource_plan_stock_picking.py
  analytic_resource_plan_stock_picking/views/analytic_resource_plan_view.xml
  analytic_resource_plan_stock_picking/views/stock_picking_view.xml
  analytic_resource_plan_stock_picking/wizard/__init__.py
  analytic_resource_plan_stock_picking/wizard/delivery.py
  analytic_resource_plan_stock_picking/wizard/delivery.xml
Labels: Approved

#147 [12.0][MIG] analytic resource plan stock picking purchase request
  analytic_resource_plan_stock_picking_purchase_request/README.rst
  analytic_resource_plan_stock_picking_purchase_request/__init__.py
  analytic_resource_plan_stock_picking_purchase_request/__manifest__.py
  analytic_resource_plan_stock_picking_purchase_request/model/__init__.py
  analytic_resource_plan_stock_picking_purchase_request/model/analytic_resource_plan_line.py
  analytic_resource_plan_stock_picking_purchase_request/tests/__init__.py
  analytic_resource_plan_stock_picking_purchase_request/tests/test_analytic_resource_plan_stock_picking_purchase_request.py
Labels: Approved

#148 [12.0][MIG]Analytic resource plan mrp
  analytic_resource_plan_mrp/README.rst
  analytic_resource_plan_mrp/__init__.py
  analytic_resource_plan_mrp/__manifest__.py
  analytic_resource_plan_mrp/models/__init__.py
  analytic_resource_plan_mrp/models/analytic_resource_plan_line.py
  analytic_resource_plan_mrp/tests/__init__.py
  analytic_resource_plan_mrp/tests/test_analytic_resource_plan_mrp.py
  analytic_resource_plan_mrp/views/analytic_resource_plan_line_view.xml
  analytic_resource_plan_mrp/wizard/__init__.py
  analytic_resource_plan_mrp/wizard/consume.py
  analytic_resource_plan_mrp/wizard/consume_view.xml
  analytic_resource_plan_mrp/wizard/produce.py
  analytic_resource_plan_mrp/wizard/produce_view.xml
Labels: Approved

#149 [12.0][MIG] analytic schedule
  analytic_schedule/README.rst
  analytic_schedule/__init__.py
  analytic_schedule/__manifest__.py
  analytic_schedule/model/__init__.py
  analytic_schedule/model/account_analytic_account.py
  analytic_schedule/model/project.py
  analytic_schedule/static/src/img/icon.png
  analytic_schedule/tests/__init__.py
  analytic_schedule/tests/test_analytic_resource_plan.py
  analytic_schedule/views/analytic_account_view.xml
Labels: Approved

#150 [12.0][MIG] analytic_contract_value to v12
  analytic_contract_value/README.rst
  analytic_contract_value/__init__.py
  analytic_contract_value/__manifest__.py
  analytic_contract_value/models/__init__.py
  analytic_contract_value/models/account_analytic_account.py
  analytic_contract_value/security/analytic_security.xml
  analytic_contract_value/tests/__init__.py
  analytic_contract_value/tests/test_analytic_contract_value.py
  analytic_contract_value/views/analytic_account_view.xml
Labels: Approved

#135 [10.0][FIX]picking type domains in analytic account
  analytic_location/model/analytic.py
Labels: Approved, Ready to merge, enhancement

#146 [12.0][MIG] analytic resource plan stock picking operating unit
  analytic_resource_plan_purchase_request/model/analytic_resource_plan_line.py
  analytic_resource_plan_purchase_request/wizard/analytic_resource_plan_line_make_purchase_request.py
  analytic_resource_plan_stock_picking/model/analytic_resource_plan_line.py
  analytic_resource_plan_stock_picking_operating_unit/README.rst
  analytic_resource_plan_stock_picking_operating_unit/__init__.py
  analytic_resource_plan_stock_picking_operating_unit/__manifest__.py
  analytic_resource_plan_stock_picking_operating_unit/model/__init__.py
  analytic_resource_plan_stock_picking_operating_unit/model/analytic_resource_plan_line.py
  analytic_resource_plan_stock_picking_operating_unit/tests/__init__.py
  analytic_resource_plan_stock_picking_operating_unit/tests/test_analytic_resource_plan_stock_picking.py
  analytic_resource_plan_stock_picking_purchase_request/tests/test_analytic_resource_plan_stock_picking_purchase_request.py
  oca_dependencies.txt
Labels: Approved

#156 [10.0][FIX] project_location
  project_location/model/project.py
Labels: Fixes issue, Ready to merge

#152 [12.0][MIG] analytic plan cost revenue
  analytic_plan/models/__init__.py
  analytic_plan/models/account_analytic_account.py
  analytic_plan/models/project.py
  analytic_plan/views/account_analytic_account_view.xml
  analytic_plan_cost_revenue/README.rst
  analytic_plan_cost_revenue/__init__.py
  analytic_plan_cost_revenue/__manifest__.py
  analytic_plan_cost_revenue/models/__init__.py
  analytic_plan_cost_revenue/models/analytic.py
  analytic_plan_cost_revenue/tests/__init__.py
  analytic_plan_cost_revenue/tests/test_analytic_plan_cost_revenue.py
  analytic_plan_cost_revenue/views/analytic_view.xml
  analytic_resource_plan/model/__init__.py
  analytic_resource_plan/model/project.py
  stock_analytic_account/model/__init__.py
  stock_analytic_account/model/project.py
Labels: Approved, Ready to merge

#157 [12.0][MIG] analytic_wip_report
  analytic_journal/__init__.py
  analytic_journal/__manifest__.py
  analytic_journal/hooks.py
  analytic_journal/model/analytic.py
  analytic_journal/model/chart_template.py
  analytic_wip_report/README.rst
  analytic_wip_report/__init__.py
  analytic_wip_report/__manifest__.py
  analytic_wip_report/i18n/analytic_wip_report.pot
  analytic_wip_report/i18n/it.po
  analytic_wip_report/i18n/sl.po
  analytic_wip_report/i18n/zh_CN.po
  analytic_wip_report/models/__init__.py
  analytic_wip_report/models/account_analytic_account.py
  analytic_wip_report/static/description/icon.png
  analytic_wip_report/tests/__init__.py
  analytic_wip_report/tests/test_analytic_wip_report.py
  analytic_wip_report/views/account_analytic_account_view.xml
  analytic_wip_report/wizards/__init__.py
  analytic_wip_report/wizards/analytic_wip_report.py
  analytic_wip_report/wizards/analytic_wip_report_view.xml
Labels: Approved

#160 [12.0][MIG] analytic wip report fiscalyear
  analytic_wip_report_fiscalyear/README.rst
  analytic_wip_report_fiscalyear/__init__.py
  analytic_wip_report_fiscalyear/__manifest__.py
  analytic_wip_report_fiscalyear/models/__init__.py
  analytic_wip_report_fiscalyear/models/account_analytic_account.py
  analytic_wip_report_fiscalyear/views/account_analytic_account_view.xml
  analytic_wip_report_fiscalyear/wizards/__init__.py
  analytic_wip_report_fiscalyear/wizards/analytic_wip_report.py
  analytic_wip_report_fiscalyear/wizards/analytic_wip_report_view.xml
Labels: Approved

#159 [12.0] analytic_wip_report_exclude_closed
  analytic_wip_report_exclude_closed/README.rst
  analytic_wip_report_exclude_closed/__init__.py
  analytic_wip_report_exclude_closed/__manifest__.py
  analytic_wip_report_exclude_closed/static/src/img/icon.png
  analytic_wip_report_exclude_closed/wizards/__init__.py
  analytic_wip_report_exclude_closed/wizards/analytic_wip_report.py
  analytic_wip_report_exclude_closed/wizards/analytic_wip_report_view.xml
Labels: Approved

#168 [MIG][12.0]mrp analytic location
  mrp_analytic_location/README.rst
  mrp_analytic_location/__init__.py
  mrp_analytic_location/__manifest__.py
  mrp_analytic_location/models/__init__.py
  mrp_analytic_location/models/mrp_production.py
  mrp_analytic_location/tests/__init__.py
  mrp_analytic_location/tests/test_mrp_analytic_location.py
  stock_location_analytic_mrp/tests/test_stock_location_analytic_mrp.py
Labels: Tested

#169 [12.0][MIG]Project mrp production
  project_mrp_production/README.rst
  project_mrp_production/__init__.py
  project_mrp_production/__manifest__.py
  project_mrp_production/security/ir.model.access.csv
  project_mrp_production/view/project_view.xml
Labels: Tested

#170 [12.0][MIG]Project cost category
  project_cost_category/README.rst
  project_cost_category/__init__.py
  project_cost_category/__manifest__.py
  project_cost_category/models/__init__.py
  project_cost_category/models/project.py
  project_cost_category/views/project_view.xml
Labels: Tested

#171 [12.0][MIG]Project percent completed
  project_percent_completed/README.rst
  project_percent_completed/__init__.py
  project_percent_completed/__manifest__.py
  project_percent_completed/model/__init__.py
  project_percent_completed/model/project.py
  project_percent_completed/static/src/img/icon.png
  project_percent_completed/view/project_view.xml
Labels: Needs review

#178 [10.0][FIX] change_management related minor fixes
  change_management_contract_value/models/change_management.py
  change_management_own_project/models/change_management.py
Labels: Fixes issue, Needs review, Ready to merge

#176 [12.0][MIG]Sale timesheet analytic journal
  sale_timesheet_analytic_journal/README.rst
  sale_timesheet_analytic_journal/__init__.py
  sale_timesheet_analytic_journal/__manifest__.py
  sale_timesheet_analytic_journal/demo/analytic_journal_data.xml
  sale_timesheet_analytic_journal/models/__init__.py
  sale_timesheet_analytic_journal/models/account_analytic_line.py
Labels: Approved

#179 [12.0][FIX]change_management_contract_value add description to change template
  change_management_contract_value/models/change_management_template.py
Labels: Fastracking, bug
